[versions]
asm = "9.4"
commons-compress = "1.23.0"
guava = "31.1-jre"
guice = "5.1.0"
jackson = "2.14.2"
jimfs = "1.2"
junit = "5.9.2"
kotlin = "1.8.10"
kotlinCoroutines = "1.6.4"
ktor = "2.2.4"
netty = "4.1.90.Final"
nettyIoUring = "0.0.19.Final"

[plugins]
dependencyLicenseReport = { id = "com.github.jk1.dependency-license-report", version = "2.1" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.13.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.46.0" }

[libraries]
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
bootstrap = { module = "org.webjars:bootstrap", version = "5.2.3" }
bootstrapTable = { module = "org.webjars.npm:bootstrap-table", version = "1.21.3" }
bouncyCastle-pkix = { module = "org.bouncycastle:bcpkix-jdk15on", version = "1.70" }
bouncyCastle-provider = { module = "org.bouncycastle:bcprov-jdk15on", version = "1.70" }
byteUnits = { module = "com.jakewharton.byteunits:byteunits", version = "0.9.1" }
clikt = { module = "com.github.ajalt.clikt:clikt", version = "3.5.2" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
fastutil = { module = "it.unimi.dsi:fastutil", version = "8.5.12" }
fernflower = { module = "org.openrs2:fernflower", version = "1.1.1" }
flyway = { module = "org.flywaydb:flyway-core", version = "9.16.1" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice-core = { module = "com.google.inject:guice", version.ref = "guice" }
guice-assistedInject = { module = "com.google.inject.extensions:guice-assistedinject", version.ref = "guice" }
h2 = { module = "com.h2database:h2", version = "2.1.214" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "5.0.1" }
inlineLogger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger", version = "1.0.4" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
javaParser = { module = "com.github.javaparser:javaparser-symbol-solver-core", version = "3.25.1" }
jdom = { module = "org.jdom:jdom2", version = "2.0.6.1" }
jgrapht = { module = "org.jgrapht:jgrapht-core", version = "1.5.1" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }
jquery = { module = "org.webjars:jquery", version = "3.6.4" }
jnr = { module = "com.github.jnr:jnr-ffi", version = "2.2.13" }
jsoup = { module = "org.jsoup:jsoup", version = "1.15.4" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version = { strictly = "5.9.2" } }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.9.2" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-autoHeadResponse = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
ktor-server-cachingHeaders = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
ktor-server-conditionalHeaders = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-defaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-forwardedHeader = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-jetty = { module = "io.ktor:ktor-server-jetty", version.ref = "ktor" }
ktor-server-thymeleaf = { module = "io.ktor:ktor-server-thymeleaf", version.ref = "ktor" }
ktor-server-webjars = { module = "io.ktor:ktor-server-webjars", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.4.6" }
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec-core = { module = "io.netty:netty-codec", version.ref = "netty" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
netty-transport = { module = "io.netty:netty-transport", version.ref = "netty" }
openrs2-natives = { module = "org.openrs2:openrs2-natives-all", version = "3.2.0" }
pf4j = { module = "org.pf4j:pf4j", version = "3.9.0" }
postgres = { module = "org.postgresql:postgresql", version = "42.6.0" }
result-core = { module = "com.michael-bull.kotlin-result:kotlin-result", version = "1.1.16" }
result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version = "1.1.16" }
runelite-client = { module = "net.runelite:client", version = "1.9.13.1" }
sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.41.2.1" }
thymeleaf-core = { module = "org.thymeleaf:thymeleaf", version = "3.1.1.RELEASE" }
thymeleaf-java8time = { module = "org.thymeleaf.extras:thymeleaf-extras-java8time", version = "3.0.4.RELEASE" }
xz = { module = "org.tukaani:xz", version = "1.9" }

[bundles]
asm = ["asm-core", "asm-commons", "asm-tree", "asm-util"]
bouncyCastle = ["bouncyCastle-pkix", "bouncyCastle-provider"]
guice = ["guice-core", "guice-assistedInject"]
ktor = [
	"ktor-serialization-jackson",
	"ktor-server-autoHeadResponse",
	"ktor-server-cachingHeaders",
	"ktor-server-conditionalHeaders",
	"ktor-server-contentNegotiation",
	"ktor-server-cors",
	"ktor-server-defaultHeaders",
	"ktor-server-forwardedHeader",
	"ktor-server-jetty",
	"ktor-server-thymeleaf",
	"ktor-server-webjars",
]
thymeleaf = ["thymeleaf-core", "thymeleaf-java8time"]
